import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import record from '../data/package_tourism.json'

export default function Info() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div>
            {
              record.map( (rec, index) => {
                return(
                  <div key={index} style={{display:'flex'}}>

                    <div style={{display:'flex', flexDirection:'row-reverse'}}>
                    <div>{rec.City}</div>
                    </div>

                  </div>

                )
              })
            }
          </div>
      </main>

    </>
  )
}