import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import record from '../data/package_tourism.json'

export default function Info() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.infoMain}>
          <div>
            {
              record.map( (rec, index) => {
                return(
                  <div key={index} style={{display:'flex', flexDirection:'row'}}>

                  <div className={styles.infoCardCont}>

                    <div className={styles.infoCard}>
                    <div>
                      <p className={styles.cityP}>{rec.City}</p>
                    </div>

                    <div>
                      <Image src='/../public/indo.png' width={200} height={100}/>
                    </div>

                    <div>
                      <p className={styles.infoP}>{rec.Place_Tourism1}</p>
                    </div>

                    </div>
                  </div>
                  </div>

                )
              })
            }
          </div>
      </main>

    </>
  )
}